config/routes.rb
Mbv2::Application.routes.draw do
  match '/mnemonics/:id/images/new', to: 'images#new', via: 'get'
  match '/:parent/:id/mnemonics/new', to: 'mnemonics#new', via: 'get'
  match '/wallposts/:id/new', to: 'wallposts#new', via: 'get'
  match '/featured_images/:id/new', to: 'featured_images#new', via: 'get'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :subtitles
  resources :comments, only: [:index, :create, :destroy]
  resources :movies, only: [:index]
  resources :hanzis
  resources :gorodishes, only: [:show, :index]
  resources :images
  resources :mnemonics
  resources :pinyindefinitions
  resources :wallposts, only: [:index, :create, :destroy]
  resources :featured_images
  resources :strokeorders, only: [:new, :create, :show, :destroy]
  root  'static_pages#home'
  match '/signup',                   to: 'users#new',           via: 'get'
  match '/signin',                   to: 'sessions#new',        via: 'get'
  match '/signout',                  to: 'sessions#destroy',    via: 'delete'
  match '/about',                    to: 'static_pages#about',  via: 'get'
  match '/search',                   to: 'hanzis#search',       via: 'get'
  match '/hurl/:input',              to: 'hanzis#hurl',         via: 'get'
  match '/select/:character',        to: 'hanzis#select',       via: 'get'

  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @hanzis_with_subtitles = Hanzi.joins(:subtitles).uniq
    @hanzis_with_mnemonics = Hanzi.includes(:mnemonics).where.not(:mnemonics => { id: nil })
    @to_be_covered_count = (@hanzis_with_subtitles - @hanzis_with_mnemonics).count
    @next = (Hanzi.all - @hanzis_with_mnemonics)[0..15]
    @mnemonic_total_count = Mnemonic.all.count
    @mnemonic_uniq_count = Hanzi.joins(:mnemonics).uniq.count
    @mnemonic_count_7_days = Hanzi.includes(:mnemonics).where(:mnemonics => { created_at: [7.days.ago..Time.zone.now] }).count
    @mnemonic_count_today = Hanzi.includes(:mnemonics).where(:mnemonics => { created_at: [Time.zone.today.beginning_of_day..Time.zone.now] }).count
    # Last three featured images
    @fimage = FeaturedImage.last
    @previous_featured_image = @fimage.previous unless FeaturedImage.last.nil?
    @previous_previous_featured_image = @previous_featured_image.previous unless @previous_featured_image.nil?
    @hsktotals = []
    @hskcovereds = []
    for hsk in 1..6
      total = Hanzi.where(HSK: hsk).uniq.count.to_f
      if total > 0
        covered = Hanzi.where(HSK: hsk).joins(:mnemonics).uniq.count.to_f
        @hsktotals << total
        @hskcovereds << covered
      end
    end        
  end

  def about
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def display_next(collection)
    render :partial => "next_hanzi", collection: collection
  end

  def fimage_preview(fimage)
    render :partial => "fimage_preview", locals: {fimage: fimage}
  end
end

app/views/static_pages/_fimage_preview.html.erb
<div class="prevnext">
  <div class="bordered">
    <div>
      <%= link_to fimage.hanzi.character, fimage, {class: "big-char hanzi"} %>
    </div>
    <div>
      <a href="/featured_images/<%= fimage.id %>">
	<img src="http://<%= S3_CONFIG["fimage_bucket"] %>.s3-eu-west-1.amazonaws.com/<%= fimage.id %>.png"
	     alt="featured image for <%= @fimage.hanzi.character %>" width="160px">
      </a>
    </div>
    <span><%= time_ago_in_words(fimage.created_at) %> ago</span><br/>
  </div>
</div>

app/views/static_pages/_next_hanzi.html.erb
<span class="single-char">
  <%= link_to next_hanzi.character, next_hanzi, { class: "hanzi" } %>
</span>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Mandarin Banana') %>
<div class="center">
<h2>About Mandarin Banana</h2>
<p>
  This website is the one I use to learn Chinese. Can you imagine how amazing it is to develop a website for learning Chinese, catering exactly to your own
  needs? At the same time, I think that the approach I use could be helpful for many people. Together, we can create a collection of awesome mnemonics and
  paintings, to make remembering Chinese characters easier and funnier than ever.
</p>
<h2>My story of learning Chinese and programming learning applications</h2>
<p>
  When starting learning Chinese, I was fascinated by learning about two concepts: Learning understanding and speaking Chinese with sentences, and
  remembering characters with the help of mnemonics. First, I learned speaking Chinese with the help of sentences split from movies. A popular software
  application for doing so is subs2srs. Of course, I used Anki to review the sentences. At first, I would have the video be played back to me and the
  Chinese characters shown, and then I would test myself to repeat what I have heard. Later, I would only have the sentence shown and try to read it aloud
  (well, in my mind). Later, I created a website like Mandarin Banana, but on my own computer using bash scripts, so nothing that
  could be used on the internet.
</p>
<p>
  After a while I realized that a mnemonic is only effective when it can be cast into a picture. So why not draw the
  picture? It makes reviewing mnemonics so much quicker. How long do you need do look at the Mona Lisa to know what she looks like, and how long would it
  take you to read a text about what Mona Lisa looks like?
</p>
<p>
  When I found Serge Gorodish' approach of incorporating the pronunciation of Chinese characters into mnemonics, I was
  thrilled. Finally, there was a way to combine learning Chinese characters and their pronunciations! But it would be a Herculean task to invent all the
  mnemonics and paint all the pictures. A community effort is needed. That's why I teach myself programming Ruby and how to use its framework Rails,
  mostly by Michael Hartl's tutorial and browsing stackexchange when I'm stuck.
</p>
<p> 
  So two years after my first Chinese scripting attempts, here we are: Mandarin Banana has been released, waiting to create a collection of memorable Hanzi
  mnemonics.
</p>
<h2>Some personal background</h2>
<div style="float:right;margin:0px 0px 20px 20px;">
  <%= image_tag "me.jpg" %>
</div>
<p>
  Hi! My name is Matthias Benjamin Schönborn, and I'm a physicist researching Photosystem II at the Free University of Berlin. In my free time, I use this
  website to learn Chinese and sometimes I even program some new features for Mandarin Banana (I have a looong wish list).
</p>
<p>
  Back in the days, when I was about to plan my master's thesis, I thought about doing the research abroad. After all, it was a good opportunity to see the
  world! So I asked around for research collaborations, and one professor offered me to go to China. I thought to myself: "I know nothing about China. At
  the same time, it seems to be such an important country. I should go and have a look!" So I stayed for almost one year in Hangzhou researching numerical
  simulations of thermal lensing in laser crystals, and I was able to spend two months travelling in China during that time.
</p>
<p>
  Long story short: It was one of the most interesting times of my life, I learned Chinese, and I met my spouse. How awesome is that?
</p>
<p>
  Also, I ended up developing Mandarin Banana. It's really fun, but my time is really limited. I can only spend a few hours each week for programming. I
  would really like to make a full time job out of developing for Mandarin Banana after finishing my PhD (hopefully in mid 2016), but for that I need to
  find a way to earn money from working on this website. Still, I remind myself frequently that the first priority is the usefulness of the website for learning
  Chinese, money is secondary. I hope you enjoy using the website as much as I do!
</p>
<h2>Acknowledgement</h2>
<p>
  Here are some people without whom this website wouldn't exist. I'd like to thank (in alphabetical order)</p>
  <ul class="about left">
    <li>An anonymous person for creating <a href="http://www.mdbg.net">mdbg.net</a> and its database, from which I use the definitions;</li>
    <li>atitarev from chinese-forums.com for creating <a href="http://www.chinese-forums.com/index.php?/topic/12580-%E3%80%8A%E5%B0%8F%E5%9F%8E%E4%B9%8B%E6%98%A5%E3%80%8Bspring-in-a-small-town/">subtitles</a> for "spring in a small town";</li>
    <li><a href="http://purl.org/net/2008,frankbruder/home">Frank Bruder</a> for making his comic lettering font publicly available;</li>
    <li>Damien Elmes for creating <a href="http://www.ankisrs.net">Anki</a>;</li>
    <li>Serge Gorodish for the invention of his <a href="http://countryoftheblind.blogspot.de/2012/01/mnemonics-for-pronouncing-chinese.html">romanization system</a>;</li>
    <li>Michael Hartl for creating <a href="http://www.railstutorial.org">railstutorial.org</a>;</li>
    <li>Khatzumoto for his creative articles on <a href="http://www.ajatt.com">ajatt.com</a>;</li>
    <li>Olle Linge for his inspiring articles on <a href="http://www.hackingchinese.com">hackingchinese.com</a>;</li>
    <li>M4RCO, Muke, Yug, Wikic, Micheletb and all other contributors for creating <a href="http://commons.wikimedia.org/wiki/Commons:Stroke_Order_Project">stroke order images</a>;</li>
    <li>Tomasz P. Szynalski and Michal Ryszard for creating <a href="http://antimoon.com">antimoon.com</a>.</li>
  </ul>
<h2>Using stuff from Mandarin Banana</h2>
<p>
  There are so many free resources on the internet that I have profited from, and I feel grateful for that. It would be the least to offer the same in
  return. Therefore, I promise that the data on Mandarin Banana will be always publicly accessible. You are free to use any data (e.g. texts, images,
  videos) for any purpose, provided that you acknowledge the respective author and Mandarin Banana, as well as to provide a link to mandarinbanana.com.
</p>
<h2>Terms of use</h2>
<p>
  Mandarin Banana will not be responsible for any damage done to you or your equipment. Use at your own risk. When submitting data to Mandarin Banana, you
  agree to licensing it <a href="http://creativecommons.org/licenses/by/4.0/">CC-BY</a>, enabling anyone to use it for any purpose, provided that you are acknowledged as the author.
</p>
</div>

app/views/static_pages/home.html.erb
<!-- Project Wonderful Ad Box Loader -->
<script type="text/javascript">
   (function(){function pw_load(){
      if(arguments.callee.z)return;else arguments.callee.z=true;
      var d=document;var s=d.createElement('script');
      var x=d.getElementsByTagName('script')[0];
      s.type='text/javascript';s.async=true;
      s.src='//www.projectwonderful.com/pwa.js';
      x.parentNode.insertBefore(s,x);}
   if (window.attachEvent){
    window.attachEvent('DOMContentLoaded',pw_load);
    window.attachEvent('onload',pw_load);}
   else{
    window.addEventListener('DOMContentLoaded',pw_load,false);
    window.addEventListener('load',pw_load,false);}})();
</script>
<!-- End Project Wonderful Ad Box Loader -->

<div class="center hero-unit">
  <div id="hero">
    <h1>MandarinBanana</h1>

    <h2>&nbsp;&nbsp;&nbsp;Remembering Chinese characters with comics and movies&nbsp;&nbsp;&nbsp;</h2>
    <br/>
    <%= link_to "first comic", featured_image_path(FeaturedImage.first), class: "btn btn-large btn-primary" unless FeaturedImage.first.nil? %>
    &nbsp;&nbsp;&nbsp;
    <%= fimage_preview(@previous_previous_featured_image) unless @previous_previous_featured_image.nil? %>
    &nbsp;&nbsp;&nbsp;
    <%= fimage_preview(@previous_featured_image) unless @previous_featured_image.nil? %>
    &nbsp;&nbsp;&nbsp;
    <%= fimage_preview(@fimage) unless @fimage.nil? %>
  </div>
</div>
<div class="ads">
<!-- Project Wonderful Ad Box Code -->
<div style="text-align:center;"><div style="display:inline-block;" id="pw_adbox_74989_1_0"></div></div>
<script type="text/javascript"></script>
<noscript><div style="text-align:center;"><div style="display:inline-block;"><map name="admap74989" id="admap74989"><area href="http://www.projectwonderful.com/out_nojs.php?r=0&c=0&id=74989&type=1" shape="rect" coords="0,0,468,60" title="" alt="" target="_blank" /></map>
<table cellpadding="0" cellspacing="0" style="width:468px;border-style:none;background-color:#ffffff;"><tr><td><img src="http://www.projectwonderful.com/nojs.php?id=74989&type=1" style="width:468px;height:60px;border-style:none;" usemap="#admap74989" alt="" /></td></tr><tr><td style="background-color:#ffffff;" colspan="1"><center><a style="font-size:10px;color:#0000ff;text-decoration:none;line-height:1.2;font-weight:bold;font-family:Tahoma, verdana,arial,helvetica,sans-serif;text-transform: none;letter-spacing:normal;text-shadow:none;white-space:normal;word-spacing:normal;" href="http://www.projectwonderful.com/advertisehere.php?id=74989&type=1&tag=105112" target="_blank">Ads by Project Wonderful!  Your ad here, right now: $0</a></center></td></tr></table></div></div>
</noscript>
<!-- End Project Wonderful Ad Box Code -->
</div>
<div class="center">
  <h1>How this works</h1>
  <p>Learning to remember Chinese characters has been a pain for a long time, but with comics and movies, it's a lot easier. Here's how it works.</p>
  <p>In each comic, all the information about a certain Chinese character—translations, pronunciation, elements—are encoded as parts of the
  comic. Consider the following example:</p>
  <h2>Sherlock Holmes in the Erechtheion</h2>
  <%= image_tag "64.png" %>
  <p>So here's Sherlock Holmes in the Erechtheion's bathroom. These two pieces of information tell us the pronunciation: <b>Sh</b>erlock Holmes is
  for <b>sh-</b>, the <b>E</b>rechtheion is for <b>-e</b>, and the bathroom is the fourth tone. Which gives:</p>
  <h2>sh + e + 4 = she4</h2>
  <p>What about the components? The monk's cowls represent "礻", a character component meaning "cult". The heap of dirt on the right hand side represents "
  土", which means "earth". This gives:</p>
  <h2>礻 + 土 = 社</h2>
  <p>But what does 社 actually mean? One of the translations is "society". To combine all this information, just read the mnemonic story once and look at
  the picture:</p>
  <p><b>Sh</b>erlock Holmes (sh-) is doing an undercover investigation in the <b>E</b>rechtheion's bathroom (-e4). There's a forbidden mysterious cult (the monk's cowls: <a href=/hurl/礻>礻</a>, the cult itself being seen as club: <a href=/hurl/社>社</a>) praying to a fossilized heap of dirt (<a href=/hurl/土>土</a>).</p>
  <br/>
  <h1>Coverage</h1>
  <br/>
  <% @hsktotals.each_with_index do |value, hsk| %>
    <span>HSK <%= hsk+1 %>: <%= @hskcovereds[hsk].round %> / <%= @hsktotals[hsk].round %></span>
    <div class="progress">
      <div class="progress-bar" role="progressbar" style="width:<%= (@hskcovereds[hsk] / @hsktotals[hsk] * 100).round %>%; background-color:#337ab7; color:white;">
	<span class="sr-only"><%= (@hskcovereds[hsk] / @hsktotals[hsk] * 100).round %>%</span>
      </div>
    </div>
  <% end %>
  <h1>What's new</h1>
    <ul class="left">
      <li>Mnemonics count: <%= @mnemonic_total_count %></li>
      <li>Chinese characters covered: <%= @mnemonic_uniq_count %></li>
      <li>Characters covered in the last seven days: <%= @mnemonic_count_7_days %></li>
      <li>Characters covered today: <%= @mnemonic_count_today %></li>
    </ul>
  <br/>
  <br/>
  <h1>To Be Continued</h1>
  <p class="center">Can you find mnemonics for these characters?</p>
  <div><p class="center"><%= display_next(@next) %></p></div>
  <p class="center">There are <%= @to_be_covered_count %> Chinese characters left to be covered in <%= link_to "the movies", movies_path %>.</p>
</div>