config/routes.rb
Mbv2::Application.routes.draw do
  match '/mnemonics/:id/images/new', to: 'images#new', via: 'get'
  match '/:parent/:id/mnemonics/new', to: 'mnemonics#new', via: 'get'
  match '/wallposts/:id/new', to: 'wallposts#new', via: 'get'
  match '/featured_images/:id/new', to: 'featured_images#new', via: 'get'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :subtitles
  resources :comments, only: [:index, :create, :destroy]
  resources :movies, only: [:index]
  resources :hanzis
  resources :gorodishes, only: [:show, :index]
  resources :images
  resources :mnemonics
  resources :pinyindefinitions
  resources :wallposts, only: [:index, :create, :destroy]
  resources :featured_images
  resources :strokeorders, only: [:new, :create, :show, :destroy]
  root  'static_pages#home'
  match '/signup',                   to: 'users#new',           via: 'get'
  match '/signin',                   to: 'sessions#new',        via: 'get'
  match '/signout',                  to: 'sessions#destroy',    via: 'delete'
  match '/about',                    to: 'static_pages#about',  via: 'get'
  match '/search',                   to: 'hanzis#search',       via: 'get'
  match '/hurl/:input',              to: 'hanzis#hurl',         via: 'get'
  match '/select/:character',        to: 'hanzis#select',       via: 'get'

  

end

app/models/subtitle.rb
class Subtitle < ActiveRecord::Base
  serialize :pinyin, JSON
  serialize :words, JSON
  belongs_to :movie
  validates :filename, presence: true, uniqueness: true
  validates :movie_id, presence: true
  has_many :comments, dependent: :destroy
  has_many :reverse_examples, foreign_key: "subtitle_id", class_name: "Example", dependent: :destroy
  has_many :expressions, through: :reverse_examples, source: :expression
  default_scope -> { order(Arel.sql('filename ASC')) }

  def set_HSK
    @HSK = 1
    if self.sentence == ""
      @HSK = 0
    end
    self.sentence.each_char do |char|
      @hanzi = Hanzi.find_by(character: char)
      if not @hanzi.nil?
        if @hanzi.HSK > @HSK
          @HSK = @hanzi.HSK
        end
      end
    end
    self.HSK = @HSK
    self.save!
  end

  def find_words
    start_index = 0
    end_index = 3
    length = 4
    @words = Array.new
    while start_index < self.sentence.length
      # puts "start_index: #{start_index}, end_index: #{end_index}"
      if end_index == self.sentence.length
        end_index -= 1
        next
      end
      candidate = self.sentence[start_index..end_index]
      # puts "candidate: #{candidate}"
      length = end_index - start_index + 1
      if length == 1
        @words.push(candidate)
        start_index = start_index + 1
        end_index = start_index + 3
      else
        unless Word.find_by(simplified: candidate).nil?
          @words.push(candidate)
          start_index = start_index + length
          end_index = start_index + 3
        else
          end_index -= 1
        end
      end
    end
    # puts @words
    self.words = @words
    self.save!
  end

  def find_pinyin
    @pinyin = Array.new
    self.words.each do |word|
      if word.length > 1
        lines = Word.find_by(simplified: word).translation.split(" // ")
        @this_pinyin = Array.new
        lines.each do |l|
          @this_pinyin.push(l.gsub(/\].*/, '').downcase[1..-1].split(" "))
        end
        @this_pinyin.transpose.each do |pinyin|
          @pinyin.push(pinyin.sort.uniq)
        end
      else
        @this_pinyin = Array.new
        @hanzi = Hanzi.find_by(character: word)
        unless @hanzi.nil?
          @hanzi.pinyindefinitions.each do |pd|
            @this_pinyin.push("#{pd.pinyin.downcase}")
          end
          @pinyin.push(@this_pinyin.sort.uniq)
        else
          @pinyin.push([word])
        end
      end
      # puts @this_pinyin.to_json
    end
    # puts @pinyin.to_json
    self.pinyin = @pinyin
    self.save!
  end

  def vocabulary(level=1)
    @vocabulary = Array.new
    if self.words.nil?
      return nil
    else
      self.words.each do |word|
        @entry = Array.new
        if word.length > 1
          @words = Word.where(simplified: word)
          unless @words.nil?
            @words.each do |this_word|
              lines = this_word.translation.split(" // ")
              lines.each do |l|
                @entry.push("[#{this_word.pinyin.downcase}] #{l}")
              end
              @vocabulary.push([word, @entry]) unless @vocabulary.include?([word, @entry]) or this_word.HSK < level
            end
          end
        else
          @hanzi = Hanzi.find_by(character: word)
          unless @hanzi.nil?
            Hanzi.find_by(character: word).pinyindefinitions.each do |pd|
              @entry.push("[#{pd.pinyin.downcase}] #{pd.definition}")
            end        
            @vocabulary.push([word, @entry]) unless @vocabulary.include?([word, @entry]) or @hanzi.HSK < level
          end
        end
      end
      return @vocabulary
    end
  end
end

app/controllers/subtitles_controller.rb
class SubtitlesController < ApplicationController
  before_action :admin_user, only: [:edit, :update, :destroy]

  def show
    store_location
    @subtitle = Subtitle.find(params[:id])
    @comments = @subtitle.comments
    @comment = current_user.comments.build if signed_in?
    @topic = "subtitle"
    @topic_id = @subtitle.id
    @vocabulary = @subtitle.vocabulary
    @pinyin = @subtitle.pinyin
  end

  def edit
    @subtitle = Subtitle.find(params[:id])
    @vocabulary = @subtitle.vocabulary
    if @subtitle.words.nil?
      @words_string = ""
    else
      @words_string = @subtitle.words.join("|")
    end
    @pinyin_array = Array.new
    if @subtitle.pinyin.nil?
      @pinyin_string = ""
    else
      @subtitle.pinyin.each do |p|
        @pinyin_array.push(p.join("/"))
      end
      @pinyin_string = @pinyin_array.join("|")
    end
  end

  def update
    if current_user.admin?
      @subtitle = Subtitle.find(params[:id])
      if !params[:subtitle][:sentence].nil?
        @subtitle.sentence = params[:subtitle][:sentence]
      end
      @subtitle.chinglish = params[:subtitle][:chinglish]
      @subtitle.english = params[:subtitle][:english]
      if !params[:subtitle][:pinyin].nil?
        @pinyin_string = params[:subtitle][:pinyin]
        @pinyin_array = @pinyin_string.split("|")
        @pinyin = Array.new
        @pinyin_array.each do |p|
          @pinyin.push(p.split("/"))
        end
        @subtitle.pinyin = @pinyin
      end
      if !params[:subtitle][:words].nil?
        @subtitle.words = params[:subtitle][:words].split("|")
      end
      @subtitle.save!
    end
    redirect_back_or root_url
  end

  private

    def admin_user
      redirect_back_or root_url unless current_user.admin? && !current_user.nil?
    end
end

app/helpers/subtitles_helper.rb
# -*- coding: utf-8 -*-
module SubtitlesHelper

  # Return id of previous subtitle
  def previous_for(subtitle)
    @subtitles = Subtitle.where(movie_id: @subtitle.movie_id)
    @previous_subtitle = @subtitles[@subtitles.index(@subtitle) - 1]
    if @previous_subtitle == @subtitles.last
      link_to "Home", '/'
    else
      link_to "<<", @previous_subtitle
    end
  end

  # Return id of next subtitle
  def next_for(subtitle)
    @subtitles = Subtitle.where(movie_id: @subtitle.movie_id)
    @next_subtitle = @subtitles[@subtitles.index(@subtitle) + 1]
    if @next_subtitle == nil
      link_to "Home", '/'
    else
      link_to ">>", @next_subtitle
    end
  end

end

app/views/subtitles/_subtitle.html.erb
<div class="center tv">

<% @file = subtitle.filename + ".webm" %>

<% if autoplay == 1 %>
  <video controls autoplay width="<%= width %>" height="<%= height %>">
    <source src="http://<%= S3_CONFIG["video_bucket"] %>.s3.amazonaws.com/<%= @file %>" type="video/webm">
  </video>
<% else %>
  <video controls preload="metadata" width="<%= width %>" height="<%= height %>">
    <source src="http://<%= S3_CONFIG["video_bucket"] %>.s3.amazonaws.com/<%= @file %>" type="video/webm">
  </video>
<% end %>

<div class="example-sentence">
  <% if extensive %>
    <% counter = 0 %>
    <% subtitle.sentence.each_char do |char| %>
      <% @sentence_hanzi = Hanzi.find_by(character: char) %>
      <% if !@sentence_hanzi.nil? %>
        <div class="unknown-char">
          <span class="big-char hanzi">
	    <% unless @pinyin.nil? %>
	      <% if @pinyin[counter].length == 1 %>
	        <% @color = "color" + @pinyin[counter][0].tr('^0-9', '') %>
	      <% else %>
	        <% @color = "color" %>
	      <% end %>
	    <% end %>
            <%= link_to @sentence_hanzi.character, @sentence_hanzi, { class: @color } %>
          </span></br>
	  <% unless @pinyin.nil? %>
            <% @pinyin[counter].each do |p| %>
    	      <span class="color<%= p.tr('^0-9', '') %>"><%= p %></span></br>
	    <% end %>
          <% end %>
	  <% @sentence_hanzi.featured_images.each do |fimage | %>
	    <div class="sentence_hanzi_fimage">
	      <a href="/featured_images/<%= fimage.id %>">
		<img src="http://<%= S3_CONFIG["fimage_bucket"] %>.s3-eu-west-1.amazonaws.com/<%= fimage.id %>.png"
		     alt="featured image for <%= fimage.hanzi.character %>"
		     width="150px">
	      </a><br/>
	    </div>
	  <% end %>
        </div>
      <% else %>
        <span class="hanzi"><%= char %></span>
      <% end %>
    <% counter += 1 %>
    <% end %>
    <% if !subtitle.sentence.empty? && subtitle.english.empty? %>
      <% if signed_in? && current_user.admin? %>
        <%= form_for(@subtitle) do |f| %>
          <%= render 'shared/error_messages', object: f.object %>

          <%= f.label :chinglish %>
          <%= f.text_area :chinglish %>

          <%= f.label :english %>
          <%= f.text_area :english %>

          </br>

          <%= f.submit "Save translations", class: "btn btn-large btn-primary" %>
        <% end %>
      <% end %>
    <% end %>

  <% else %>
    <% subtitle.sentence.each_char do |char| %>
      <span class="big-char hanzi"><a href="/hurl/<%= char %>"><%= char %></a></span>
    <% end %>
  <% end %>  
  <% if morelink %>
    &nbsp;<a href="/subtitles/<%= subtitle.id %>" class="morelink">&rarr;</a><br/>
  <% end %>
  <div class="chinglish"><%= subtitle.chinglish %></div>
  <div class="english"><%= subtitle.english %></div>
</div>

<% if !@subtitle.nil? && !@vocabulary.nil? %>
  <div class="vocabulary">
    <table>
      <% @vocabulary.each do |v| %>
        <tr>
          <td class="voc-left">
	    <% v[0].each_char do |char| %>
	      <a href="/hurl/<%= char %>"><%= char %></a>
	    <% end %>
	  </td>
          <td class="voc-right">
	    <% v[1].each do |w| %>
	      <%= w %><br/>
	    <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
<% end %>

</div>

app/views/subtitles/edit.html.erb
<% provide(:title, @subtitle.sentence) %>
<h1><%= Movie.find(@subtitle.movie_id).title %></h1>

<div class="center">
  <%= render partial: "subtitle", locals: {morelink: false, subtitle: @subtitle, autoplay: 1, width: 640, height: 390, extensive: true} %>

  <%= form_for(@subtitle) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :sentence %>
    <%= f.text_field :sentence %>

    <%= f.label :words %>
    <%= f.text_field :words, value: @words_string %>

    <%= f.label :pinyin %>
    <%= f.text_area :pinyin, value: @pinyin_string %>

    <%= f.label :chinglish %>
    <%= f.text_area :chinglish %>

    <%= f.label :english %>
    <%= f.text_area :english %>

    <%= f.label :filename %>
    <%= f.text_field :filename %>

    </br>

    <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
  <% end %>

</div>

app/views/subtitles/embed.html.erb
<!DOCTYPE html>
<html>
  <body>
    <%= @subtitle.sentence %>
  </body>
</html>

app/views/subtitles/embed_comments.html.erb
<!DOCTYPE html>
<html>
  <body>
    <% if @subtitle.comments.any? %>
    <ol class="comments">
      <%= render @comments %>
    </ol>
    <% end %>
  </body>
</html>

app/views/subtitles/new.html.erb
<h1>Subtitles#new</h1>
<p>Find me in app/views/subtitles/new.html.erb</p>

app/views/subtitles/show.html.erb
<% provide(:title, @subtitle.sentence) %>
<h1><%= Movie.find(@subtitle.movie_id).title %></h1>

<div class="center">
  <div class="sub-navigation">
    <%= previous_for @subtitle %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= next_for @subtitle %>
  </div>

  <% if signed_in? %>
    <% if current_user.admin? %>
      <br/><%= link_to "edit subtitle", edit_subtitle_path(@subtitle) %><br/>
    <% end %>
  <% end %>

  <%= render partial: "subtitle", locals: {morelink: false, subtitle: @subtitle, autoplay: 1, width: 640, height: 390, extensive: true} %>

  <div class="sub-navigation">
    <%= previous_for @subtitle %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= next_for @subtitle %>
  </div>

  <% if @subtitle.comments.any? %>
  <div>
    <h3> Comments (<%= @subtitle.comments.count %>)</h3>
    <ol class="comments">
      <%= render @comments %>
    </ol>
  </div>
  <% end %>

  <% if signed_in? %>
    <% if !@subtitle.comments.any? %>
      <h2>Write the first comment</h2>
    <% end %>
    <div>
      <%= render 'shared/comment_form' %>
    </div>
  <% else %>
    <p class="center">Please log in to post comments.</p>
  <% end %>

</div>