config/routes.rb
Mbv2::Application.routes.draw do
  match '/mnemonics/:id/images/new', to: 'images#new', via: 'get'
  match '/:parent/:id/mnemonics/new', to: 'mnemonics#new', via: 'get'
  match '/wallposts/:id/new', to: 'wallposts#new', via: 'get'
  match '/featured_images/:id/new', to: 'featured_images#new', via: 'get'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :subtitles
  resources :comments, only: [:index, :create, :destroy]
  resources :movies, only: [:index]
  resources :hanzis
  resources :gorodishes, only: [:show, :index]
  resources :images
  resources :mnemonics
  resources :pinyindefinitions
  resources :wallposts, only: [:index, :create, :destroy]
  resources :featured_images
  resources :strokeorders, only: [:new, :create, :show, :destroy]
  root  'static_pages#home'
  match '/signup',                   to: 'users#new',           via: 'get'
  match '/signin',                   to: 'sessions#new',        via: 'get'
  match '/signout',                  to: 'sessions#destroy',    via: 'delete'
  match '/about',                    to: 'static_pages#about',  via: 'get'
  match '/search',                   to: 'hanzis#search',       via: 'get'
  match '/hurl/:input',              to: 'hanzis#hurl',         via: 'get'
  match '/select/:character',        to: 'hanzis#select',       via: 'get'

  

end

app/models/featured_image.rb
class FeaturedImage < ActiveRecord::Base
  validates :data, presence: true
  validates :mnemonic_aide, presence: true
  validates :hanzi_id, presence: true
  validates :pinyindefinition_id, presence: true
  validates :commentary, presence: true
  default_scope -> { order(Arel.sql('created_at ASC')) }
  belongs_to :hanzi
  belongs_to :pinyindefinition

  has_many :examples, through: :hanzi
  has_many :subtitles, through: :examples


  def next
    FeaturedImage.where("created_at > ?", self.created_at).first
  end

  def previous
    FeaturedImage.where("created_at < ?", self.created_at).last
  end
end

app/controllers/featured_images_controller.rb
# -*- coding: utf-8 -*-
class FeaturedImagesController < ApplicationController
  before_action :signed_in_user, only: [:new, :edit, :update, :destroy]
  before_action :admin_user,     only: [:new, :edit, :update, :destroy]

  def index
    @featured_images = FeaturedImage.paginate(page: params[:page], :per_page => 25)
  end

  def new
    @fimage = FeaturedImage.new
    @image = Image.find(params[:id])
    @mnemonic = @image.mnemonic
    @pd = @mnemonic.pinyindefinition
    @hanzi = @pd.hanzi
  end

  def create
    @fimage = FeaturedImage.new(fimage_params)
    if @fimage.save
      flash[:success] = "Image featured."
      s3 = Aws::S3.new(:access_key_id => ENV["S3_KEY_ID"], :secret_access_key => ENV["S3_SECRET"])
      bucket = s3.buckets[S3_CONFIG["fimage_bucket"]]
      @name = @fimage.id.to_s + ".png"
      @png = Base64.decode64(@fimage.data['data:image/png;base64,'.length .. -1])
      obj = bucket.objects.create(@name, @png, {content_type: "image/png", ac1: "public_read"})
    else
      flash[:error] = "Oh noes! Something went wrong!"
    end
    redirect_to root_url
  end

  def show
    @fimage = FeaturedImage.find(params[:id])
    @aide = @fimage.mnemonic_aide.gsub /([^\p{ASCII}—Øüäöß])/, '<a href=/hurl/\1>\1</a>'
    @commentary = @fimage.commentary.gsub /([^\p{ASCII}—Øüäöß])/, '<a href=/hurl/\1>\1</a>'
    @hanzi = Hanzi.find(@fimage.hanzi_id)
    @gbeginning = Gorodish.find_by(element: @fimage.pinyindefinition.gbeginning)
    @gending = Gorodish.find_by(element: @fimage.pinyindefinition.gending)
    @examples = @hanzi.subtitles.limit(7)
    @comments = @hanzi.comments
    @comment = current_user.comments.build if signed_in?
    @topic = "hanzi"
    @topic_id = @hanzi.id
    @stroke_order = check_stroke_order(@hanzi.character)
    @gorodishes_all = []
    @hanzi.pinyindefinitions.each do |pd|
      if pd.gbeginning != ""
        @gorodishes_all.append(Gorodish.find_by(element: pd.gbeginning))
      end
      if pd.gending != ""
        @gorodishes_all.append(Gorodish.find_by(element: pd.gending))
      end
    end
    @gorodishes = @gorodishes_all.uniq
    @appearances = Hanzi.where('components LIKE ?', "%#{@hanzi.character}%")
    @appearances_with_mnemonics = @appearances.joins(:mnemonics)
    @appearances_ids = @appearances.dup.to_a
    @appearances_ids.collect! do |h|
      h.id
    end
    @appearances_fimages = FeaturedImage.where(:hanzi_id => @appearances_ids)
    @dictionary = @appearances_fimages.dup.to_a
    @dictionary.collect! do |d|
      [d.id, d.hanzi_id]
    end
    @previous_featured_image = @fimage.previous
    @first_featured_image = FeaturedImage.first
    @next_featured_image = @fimage.next
    @last_featured_image = FeaturedImage.last
    if @fimage == @last_featured_image or @next_featured_image == @last_featured_image
      @last_featured_image = nil
    end
    if @fimage == @first_featured_image or @previous_featured_image == @first_featured_image
      @first_featured_image = nil
    end
    if @hanzi.simplifieds.any?
      @words = Word.where('traditional LIKE ?', "%#{@hanzi.character}%").paginate(page: params[:page], per_page: 40)
    else
      @words = Word.where('simplified LIKE ?', "%#{@hanzi.character}%").paginate(page: params[:page], per_page: 40)
    end
    store_location
  end

  def edit
    @fimage = FeaturedImage.find(params[:id])
    @hanzi = Hanzi.find(@fimage.hanzi_id)
  end

  def update
    @fimage = FeaturedImage.find(params[:id])
    if @fimage.update_attributes(fimage_params)
      flash[:success] = "Featured Image updated!"
    else
      flash[:error] = "Featured Image unchanged!"
    end
    redirect_to root_url
  end

  private

    def check_stroke_order(character)      
      if Rails.application.assets.find_asset 'stroke-order-imgs/' + character + '-order.gif'
        return 'stroke-order-imgs/' + character + '-order.gif'
      elsif Rails.application.assets.find_asset 'stroke-order-imgs/' + character + '-red.png'
        return 'stroke-order-imgs/' + character + '-red.png'
      elsif Rails.application.assets.find_asset 'stroke-order-imgs/' + character + '-bw.png'
        return 'stroke-order-imgs/' + character + '-bw.png'
      else
        return nil
      end
    end

    def admin_user
      redirect_to root_url unless current_user.admin? && !current_user.nil?
    end

    def fimage_params
      params.require(:featured_image).permit(:data, :commentary, :mnemonic_aide, :hanzi_id, :pinyindefinition_id)
    end
end

app/helpers/featured_images_helper.rb
# -*- coding: utf-8 -*-
module FeaturedImagesHelper
end

app/views/featured_images/edit.html.erb
<h1>Edit featured image for <%= @hanzi.character %></h1>

<div class="center">
  <div>
    <img src="<%= @fimage.data %>" alt="featured image">
  </div>
  <div>
    <%= render @hanzi %>
  </div>
  <br/><br/>
  <div>
    <%= form_for(@fimage) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div>
	<%= f.text_area :commentary %>
	<%= f.text_area :mnemonic_aide %>
      </div>
      <%= f.submit "Submit", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>

</div>

app/views/featured_images/index.csv.erb
<% if signed_in? %>
  <% FeaturedImage.all.each do |fimage| %>
    <% @id = fimage.id %>
    <% if [101].include? @id  %>
      <% next %>
    <% end %>
    <% @pd = fimage.pinyindefinition %>
    <% @p1 = @pd.pinyin %>
    <% @p2 = "= " + @pd.gbeginning + " + " + @pd.gending %>
    <% @hanzi = fimage.hanzi %>
    <% if @hanzi.components != '' %>
      <% @dec = @hanzi.character + "=" + @hanzi.components.split(//).join('+').to_s %>
    <% else %>
      <% @dec = " " %>
    <% end %>
    <% @def = fimage.pinyindefinition.definition %>
    <% @appearances = "" %>
    <% Hanzi.where('components LIKE ?', "%#{@hanzi.character}%").each do |h| %>
      <% @appearances += h.character %>
    <% end %>
    <% @story = fimage.mnemonic_aide %>
    <% @subtitles = "" %>
    <% fimage.subtitles.limit(7).each do |subtitle| %>
      <% unless subtitle == nil %>
        <% @subtitles += subtitle.filename + ":" + subtitle.sentence + "_" + subtitle.id.to_s + "|" %>
      <% end %>
    <% end %>
    <% @data = fimage.data %>
    <% @data.strip! %>
    <% @data.delete!("\n\r") %>
<%= CSV.generate_line([fimage.hanzi.character, @p1, @p2, @dec, @def, @appearances, @data, @story, @id, @subtitles], col_sep: "\t", quote_char: "\0", row_sep: ?\t).html_safe %>
  <% end %>
<% end %>

app/views/featured_images/index.html.erb
<% provide(:title, 'Index') %>
<h1>Featured Images Index</h1>

<div class="center">
  <ul class="fimages-ul">
    <% @featured_images.each do |fimage| %>
      <li>
	<a href="/featured_images/<%= fimage.id %>">
	  <img src="http://<%= S3_CONFIG["fimage_bucket"] %>.s3-eu-west-1.amazonaws.com/<%= fimage.id %>.png"
	       alt="featured image for <%= fimage.hanzi.character %>"
	       width="150px">
	</a>
	<br/>
	<div class="big-char hanzi">
	  <%= link_to fimage.hanzi.character, fimage %>
	</div>
      </li>
    <% end %>
  </ul>
  <%= will_paginate %>
</div>

app/views/featured_images/new.html.erb
<h1>Feature an image for <%= @hanzi.character %></h1>
<div class="center">
  <div class="center">
    <%= render partial: "images/image", locals: {width: 640, image: @image} %>
  </div>
  <div class="center">
    <%= render @mnemonic %>
  </div>
  <div class="center shrink">
    <%= render @hanzi %>
  </div>
  <br/><br/>
  <div>
    <%= form_for(@fimage) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div>
	<%= f.text_area :commentary, placeholder: "..." %>
	<%= f.text_area :mnemonic_aide, value: @mnemonic.aide %>
	<%= f.hidden_field :data, value: @image.data %>
	<%= f.hidden_field :hanzi_id, value: @hanzi.id %>
	<%= f.hidden_field :pinyindefinition_id, value: @mnemonic.pinyindefinition.id %>
      </div>
      <%= f.submit "Submit", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>

</div>

app/views/featured_images/show.html.erb
<!-- Project Wonderful Ad Box Loader -->
<script type="text/javascript">
   (function(){function pw_load(){
      if(arguments.callee.z)return;else arguments.callee.z=true;
      var d=document;var s=d.createElement('script');
      var x=d.getElementsByTagName('script')[0];
      s.type='text/javascript';s.async=true;
      s.src='//www.projectwonderful.com/pwa.js';
      x.parentNode.insertBefore(s,x);}
   if (window.attachEvent){
    window.attachEvent('DOMContentLoaded',pw_load);
    window.attachEvent('onload',pw_load);}
   else{
    window.addEventListener('DOMContentLoaded',pw_load,false);
    window.addEventListener('load',pw_load,false);}})();
</script>
<!-- End Project Wonderful Ad Box Loader -->

<% provide(:title, @hanzi.character) %>

<div class="center">
  <div class="header">
    <div class="headerhanzicircle"><div class="headerhanzi hanzi"><%= @hanzi.character %></div></div>
    <div class="fimagepinyin">
      <span class="firstline">
        <%= link_to @fimage.pinyindefinition.pinyin, @fimage.pinyindefinition %>
      </span><br/>
      <span class="secondline">
	= 
	<%= link_to @gbeginning.element, @gbeginning %>
	+
	<%= link_to @gending.element, @gending %>
      </span>
    </div>
    <div class="fimagedefinition">
      <%= @fimage.pinyindefinition.definition %>
    </div>
  </div>

    <div class="firstlast">
      <% if !@first_featured_image.nil? %>
        <div class="bordered">
  	  <span>first:</span><br/>
	  <%= link_to "«", @first_featured_image %>
	</div>
      <% end %>
    </div>

    <div class="prevnext">
      <% if !@previous_featured_image.nil? %>
        <div class="bordered">
	  <span>previous:</span><br/>
	  <span>
	    <%= link_to @previous_featured_image.hanzi.character, @previous_featured_image, {class: "big-char hanzi"} %>
	  </span>
	  <br/>
	  <span>
	    <a href="/featured_images/<%= @previous_featured_image.id %>">
	      <img src="http://<%= S3_CONFIG["fimage_bucket"] %>.s3-eu-west-1.amazonaws.com/<%= @previous_featured_image.id %>.png"
		   alt="featured image for <%= @previous_featured_image.hanzi.character %>"
		   class="previous_next_image">
	    </a>
	  </span>
	</div>
      <% end %>
    </div>


    <div class="feature">
      <img src="http://<%= S3_CONFIG["fimage_bucket"] %>.s3-eu-west-1.amazonaws.com/<%= @fimage.id %>.png"
	   alt="featured image for <%= @hanzi.character %>">
      <div class="featured_mnemonic">
	<%= @aide.html_safe %>
      </div>
    </div>

    <div class="prevnext">
      <% if !@next_featured_image.nil? %>
        <div class="bordered">
	  <span>next:</span><br/>
	  <span>
	    <%= link_to @next_featured_image.hanzi.character, @next_featured_image, {class: "big-char hanzi"} %>
	  </span>
	  <br/>
	  <span>
	    <a href="/featured_images/<%= @next_featured_image.id %>">
	      <img src="http://<%= S3_CONFIG["fimage_bucket"] %>.s3-eu-west-1.amazonaws.com/<%= @next_featured_image.id %>.png"
		   alt="featured image for <%= @next_featured_image.hanzi.character %>"
		   class="previous_next_image">
	    </a>
	  </span>
	</div class="bordered">
      <% end %>
    </div>

    <div class="firstlast">
      <% if !@last_featured_image.nil? %>
        <div class="bordered">
  	  <span>last:</span><br/>
	  <%= link_to "»", @last_featured_image %>
	</div>
      <% end %>
    </div>

  </div>
  <div class="ads">
<!-- Project Wonderful Ad Box Code -->
<div style="text-align:center;"><div style="display:inline-block;" id="pw_adbox_74989_1_0"></div></div>
<script type="text/javascript"></script>
<noscript><div style="text-align:center;"><div style="display:inline-block;"><map name="admap74989" id="admap74989"><area href="http://www.projectwonderful.com/out_nojs.php?r=0&c=0&id=74989&type=1" shape="rect" coords="0,0,468,60" title="" alt="" target="_blank" /></map>
<table cellpadding="0" cellspacing="0" style="width:468px;border-style:none;background-color:#ffffff;"><tr><td><img src="http://www.projectwonderful.com/nojs.php?id=74989&type=1" style="width:468px;height:60px;border-style:none;" usemap="#admap74989" alt="" /></td></tr><tr><td style="background-color:#ffffff;" colspan="1"><center><a style="font-size:10px;color:#0000ff;text-decoration:none;line-height:1.2;font-weight:bold;font-family:Tahoma, verdana,arial,helvetica,sans-serif;text-transform: none;letter-spacing:normal;text-shadow:none;white-space:normal;word-spacing:normal;" href="http://www.projectwonderful.com/advertisehere.php?id=74989&type=1&tag=105112" target="_blank">Ads by Project Wonderful!  Your ad here, right now: $0</a></center></td></tr></table></div></div>
</noscript>
<!-- End Project Wonderful Ad Box Code -->
  </div>
  <div class="center shrink">
    <%= @commentary.html_safe %>
  </div>
  <br/>

  <% if @hanzi.components != '' %>
    <h2>Composition: <span class="hanzi"><%= @hanzi.character %> = <%= @hanzi.components.split(//).join(' + ') %></span></h2>
    <div class="center decomposition_container">
      <%= render @hanzi %>
    </div>
  <% else %>
    <h2><span class="hanzi"><%= @hanzi.character %></span> can not be decomposed into smaller units.</h2>
    <div class="center decomposition_container">
      <%= render @hanzi %>
    </div>      
  <% end %>

  <% if !@stroke_order.nil? %>
    <h2>Wikimedia Commons:Stroke Order Project</h2>
    <a href="http://commons.wikimedia.org/wiki/Commons:Stroke_Order_Project" target="_blank">
      <%= image_tag @stroke_order, class: "stroke_order_image" %>
    </a>
  <% end %>

  <div class="center">
    <%= render partial: "hanzis/appearance", controller: Hanzi %>
  </div>

  <div class="center">
    <%= render partial: "hanzis/tradsimp", controller: Hanzi %>
  </div>

  <div class="center">
    <%= render partial: "hanzis/hsk", controller: Hanzi %>
  </div>

  <div class="center">
    <%= render partial: "hanzis/pronunciations", controller: Hanzi %>
  </div>

  <div class="center">
    <%= render partial: "hanzis/words", controller: Hanzi %>
  </div>

  <% if @examples.any? %>
    <h2>Example sentences for <span class="hanzi"><%= @hanzi.character %></span></h2>
    <div class="center">
      <%= render partial: "subtitles/subtitle", collection: @examples, locals: {morelink: true, autoplay: 0, width: 250, height: 150, extensive: false} %>
    </div>
  <% else %>
    <h2>There are no example sentences for this character.</h2>
  <% end %>

  <h2>See <span class="hanzi"><%= @hanzi.character %></span> on (opens in new window/tab)</h2>
  <div class="center">
    <a target="_blank" href="http://hanzicraft.com/character/<%= @hanzi.character %>">Hanzicraft</a><br/>
    <a target="_blank" href="http://www.mdbg.net/chindict/chindict.php?page=worddict&wdrst=0&wdqb=<%= @hanzi.character %>">MDBG</a><br/>
    <a target="_blank" href="http://en.wikipedia.org/wiki/<%= @hanzi.character %>">The English Wikipedia</a><br/>
    <a target="_blank" href="https://en.wiktionary.org/wiki/<%= @hanzi.character %>">The English Wiktionary</a><br/>
    <a target="_blank" href="http://stroke-order.learningweb.moe.edu.tw/characterQueryResult.do?word=<%= @hanzi.character %>">stroke-order.learningweb.moe.edu.tw</a><br/>
    <a target="_blank" href="http://tatoeba.org/eng/sentences/search?query=<%= @hanzi.character %>&from=cmn&to=und">Tatoeba</a><br/>
  </div>

  <% if @hanzi.comments.any? %>
    <div>
      <h2> Comments (<%= @hanzi.comments.count %>)</h2>
      <ol class="comments">
	<%= render @comments %>
      </ol>
    </div>
  <% end %>

  <% if signed_in? %>
    <% if !@hanzi.comments.any? %>
      <h2>Write the first comment</h2>
    <% end %>
    <div>
      <%= render 'shared/comment_form' %>
    </div>
  <% else %>
    <h2>Log in to write the first comment.</h2>
  <% end %>
  <br/>

  <% if signed_in? && current_user.admin? %>
    <br/>
    <div class="center">
      <%= link_to "Edit hanzi", edit_hanzi_path(@hanzi) %>
      | <%= link_to "New PD", new_pinyindefinition_path(:hanzi_id => @hanzi.id) %>
      | <%= link_to "Edit featured image", edit_featured_image_path(@fimage) %>
      | <%= link_to "Fimages download", featured_images_path(format: :csv) %>
      | <%= link_to "Mnemonics download", mnemonics_path(format: :csv) %>
    </div>
<% end %>


</div>

app/views/featured_images/update.html.erb
<h1>FeaturedImages#update</h1>
<p>Find me in app/views/featured_images/update.html.erb</p>