config/routes.rb
Mbv2::Application.routes.draw do
  match '/mnemonics/:id/images/new', to: 'images#new', via: 'get'
  match '/:parent/:id/mnemonics/new', to: 'mnemonics#new', via: 'get'
  match '/wallposts/:id/new', to: 'wallposts#new', via: 'get'
  match '/featured_images/:id/new', to: 'featured_images#new', via: 'get'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :subtitles
  resources :comments, only: [:index, :create, :destroy]
  resources :movies, only: [:index]
  resources :hanzis
  resources :gorodishes, only: [:show, :index]
  resources :images
  resources :mnemonics
  resources :pinyindefinitions
  resources :wallposts, only: [:index, :create, :destroy]
  resources :featured_images
  resources :strokeorders, only: [:new, :create, :show, :destroy]
  root  'static_pages#home'
  match '/signup',                   to: 'users#new',           via: 'get'
  match '/signin',                   to: 'sessions#new',        via: 'get'
  match '/signout',                  to: 'sessions#destroy',    via: 'delete'
  match '/about',                    to: 'static_pages#about',  via: 'get'
  match '/search',                   to: 'hanzis#search',       via: 'get'
  match '/hurl/:input',              to: 'hanzis#hurl',         via: 'get'
  match '/select/:character',        to: 'hanzis#select',       via: 'get'

  

end

app/models/hanzi.rb
class Hanzi < ActiveRecord::Base
  validates :character, presence: true, length: { maximum: 1 }, uniqueness: true
  has_many :pinyindefinitions, dependent: :destroy  
  has_many :mnemonics, through: :pinyindefinitions
  has_many :images, through: :mnemonics
  has_many :examples, foreign_key: "expression_id", dependent: :destroy
  has_many :subtitles, through: :examples, source: :subtitle
  has_many :comments, dependent: :destroy
  has_many :simplifieds, foreign_key: "trad_id", dependent: :destroy
  has_many :simplified_variants, through: :simplifieds, source: :simp
  has_many :traditionals, foreign_key: "simp_id", class_name: "Simplified", dependent: :destroy
  has_many :traditional_variants, through: :traditionals, source: :trad
  has_many :featured_images
  has_many :strokeorders

  default_scope { order(:HSK, frequency: :desc) }

  def simplified_by?(other_hanzi)
    simplifieds.find_by(simp_id: other_hanzi.id)
  end

  def simplify_by!(other_hanzi)
    simplifieds.create!(simp_id: other_hanzi.id)
  end
end

app/controllers/hanzis_controller.rb
class HanzisController < ApplicationController
  before_action :admin_user, only: [:edit, :update]

  def index
    @hanzis = Hanzi.paginate(page: params[:page], :per_page => 500)
  end

  def search
    @hanzi = Hanzi.find_by(character: "#{params[:character]}")
    if @hanzi.nil? then
      flash[:error] = "I didn't find anything for \"" + "#{params[:character]}" + "\"."
      redirect_back_or root_url
    else
      redirect_to hanzi_url(@hanzi.id)
    end    
  end

  def hurl
    @hanzi = Hanzi.find_by(character: params[:input])
    if @hanzi.nil?
      redirect_to root_url
    else
      redirect_to @hanzi
    end
  end

  def show
    @hanzi = Hanzi.find(params[:id])
    if @hanzi.featured_images.count > 1
      redirect_to "/select/#{@hanzi.id}"
    elsif @hanzi.featured_images.count == 1
      redirect_to @hanzi.featured_images.first
    end
    @examples = @hanzi.subtitles.limit(7)
    @comments = @hanzi.comments
    @comment = current_user.comments.build if signed_in?
    @topic = "hanzi"
    @topic_id = @hanzi.id
    @stroke_order = check_stroke_order(@hanzi.character)
    @gorodishes_all = []
    @hanzi.pinyindefinitions.each do |pd|
      if pd.gbeginning != ""
        @gorodishes_all.append(Gorodish.find_by(element: pd.gbeginning))
      end
      if pd.gending != ""
        @gorodishes_all.append(Gorodish.find_by(element: pd.gending))
      end
    end
    @gorodishes = @gorodishes_all.uniq
    @appearances = Hanzi.where('components LIKE ?', "%#{@hanzi.character}%")
    @appearances_with_mnemonics = @appearances.joins(:mnemonics)
    @appearances_ids = @appearances.dup.to_a
    @appearances_ids.collect! do |h|
      h.id
    end
    @appearances_fimages = FeaturedImage.where(:hanzi_id => @appearances_ids)
    @dictionary = @appearances_fimages.dup.to_a
    @dictionary.collect! do |d|
      [d.id, d.hanzi_id]
    end
    if @hanzi.simplifieds.any?
      @words = Word.where('traditional LIKE ?', "%#{@hanzi.character}%").paginate(page: params[:page], per_page: 40)
    else
      @words = Word.where('simplified LIKE ?', "%#{@hanzi.character}%").paginate(page: params[:page], per_page: 40)
    end
    @strokeorders = @hanzi.strokeorders
    store_location
  end

  def select
    @hanzi = Hanzi.find(params[:character])
    @fimages = @hanzi.featured_images
  end

  def edit
    @hanzi = Hanzi.find(params[:id])
    @atoms = Hanzi.where(components: "")
  end

  def update
    @hanzi = Hanzi.find(params[:id])
    if @hanzi.update_attributes(hanzi_params)
      flash[:success] = "Hanzi updated"
      redirect_to @hanzi
    else
      render 'edit'
    end
  end

  private

    def hanzi_params
      params.require(:hanzi).permit(:components)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

    def check_stroke_order(character)      
      if Rails.application.assets.find_asset 'stroke-order-imgs/' + character + '-order.gif'
        return 'stroke-order-imgs/' + character + '-order.gif'
      elsif Rails.application.assets.find_asset 'stroke-order-imgs/' + character + '-red.png'
        return 'stroke-order-imgs/' + character + '-red.png'
      elsif Rails.application.assets.find_asset 'stroke-order-imgs/' + character + '-bw.png'
        return 'stroke-order-imgs/' + character + '-bw.png'
      else
        return nil
      end
    end
end

app/helpers/hanzis_helper.rb
module HanzisHelper
  def check_for_fimages dictionary, hanzi_id
    @fimage_ids = dictionary.transpose[0]
    @fimage_hanzi_ids = dictionary.transpose[1]
    if @fimage_hanzi_ids.nil?
      @fimage_hanzi_ids_indices = []
    else
      @fimage_hanzi_ids_indices = @fimage_hanzi_ids.size.times.select { |i| @fimage_hanzi_ids[i] == hanzi_id }
    end
    @ids = []
    @fimage_hanzi_ids_indices.each do |i|
      @ids.push(@fimage_ids[i])
    end
    return @ids
  end
end

app/views/hanzis/_appearance.html.erb
<% if !@appearances.empty? %>
  <% if not @hanzi.nil? %>
    <h2><span class="hanzi"><%= @hanzi.character %></span> appears as component in</h2>
  <% end %>
  <div class="appearances center">
    <% @appearances.each do |a| %>
      <% @images = check_for_fimages(@dictionary, a.id) %>
      <% if not @images.empty? %>
        <div class="appearance">
  	  <a href="/hanzis/<%= a.id %>" class="big-char hanzi"><%= a.character %></a>
	  <br/>
          <% @images.each do |fimage | %>
       	    <a href="http://<%= S3_CONFIG["fimage_bucket"] %>.s3-eu-west-1.amazonaws.com/<%= fimage %>.png">
	      <img src="http://<%= S3_CONFIG["fimage_bucket"] %>.s3-eu-west-1.amazonaws.com/<%= fimage %>.png" alt="featured image for <%= a.character %>" width="150px">
	    </a>
	  <% end %>
	</div>
      <% else %>
	<% if @appearances_with_mnemonics.include?(a) %>
  	  <a href="/hanzis/<%= a.id %>" class="big-char has-mnemonic hanzi"><%= a.character %></a>
	<% else %> 
          <a href="/hanzis/<%= a.id %>" class="big-char hanzi"><%= a.character %></a>
	<% end %>
      <% end %>
    <% end %>
  </div>
<% else %>
  <h2><span class="hanzi"><%= @hanzi.character %></span> is not a component of another character.</h2>
<% end %>

app/views/hanzis/_hanzi.html.erb
<table class="hanzitable">
  <tr class="definition-row">
    <td>
      <span class="single-char hanzi">
	<%= link_to hanzi.character, hanzi %>
      </span>
    </td>
    <td>
      <table class="hanzitable">
	<% hanzi.pinyindefinitions.each do |pinyindefinition| %>
	  <tr>
	    <td style="white-space:nowrap; vertical-align: top; padding: 5px;">
	      <%= link_to pinyindefinition.pinyin, pinyindefinition %>
	      <% if pinyindefinition.gbeginning.present? %>
	        =<br/>
	        <a href="/gorodishes/<%= Gorodish.find_by(element: pinyindefinition.gbeginning).id %>">
	          <%= pinyindefinition.gbeginning %>
		</a>
		+
		<a href="/gorodishes/<%= Gorodish.find_by(element: pinyindefinition.gending).id %>">
		  <%= pinyindefinition.gending %>
		</a>
	      <% end %>	    
	    </td>
	    <td style="padding: 5px;">
	      <p>
		<%= pinyindefinition.definition %> |
     		<a href="/pinyindefinitions/<%= pinyindefinition.id %>/mnemonics/new">
		  add a mnemonic for this meaning of <span class="smallhanzi"><%= hanzi.character %></span>
		</a>
		<% if signed_in? && current_user.admin? %>
  	          | <%= link_to "update", edit_pinyindefinition_path(pinyindefinition) %>
	          | <%= link_to "delete", pinyindefinition, method: :delete, data: { confirm: "Are you sure?" } %>
		<% end %>
	      </p>
	      <% pinyindefinition.mnemonics.each do |mnemonic| %>
	        <%= render mnemonic %><br/>
	      <% end %>
	    </td>
	  </tr>
        <% end %>
      </table>
    </td>
  </tr>
  <% if !hanzi.components.empty? %>
    <% hanzi.components.each_char do |c| %>
      <tr>
	<td class="decomposition">
	  <span class="smallhanzi">
	    <%= hanzi.character %>
	  <br/>
	  <span>
	    = 
	  </span>
	  <br/>
	  <span class="smallhanzi">
	    <%= hanzi.components.split(//).join('	</span><br/><span>+</span><br/><span>').html_safe %>
	  </span>
	</td>
	<td>
	  <% @c_hanzi = Hanzi.find_by(character: c) %>
	  <%= render partial: "hanzis/hanzi", locals: {hanzi: @c_hanzi} unless @c_hanzi.nil? %>
	</td>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/hanzis/_hsk.html.erb
<% unless @hanzi.HSK == nil %>
  <% if @hanzi.HSK < 7 %>
    <h2>HSK level: <%= @hanzi.HSK %></h2>
  <% else %>
    <h2><span class="hanzi"><%= @hanzi.character %></span> is not part of the HSK.</h2>
  <% end %>
<% end %>

app/views/hanzis/_pronunciations.html.erb
<% if !@gorodishes[0].nil? %>
<h2>Pronunciation: Gorodish elements and their mnemonics (<%= link_to "what's this?", "/gorodishes/" %>)</h2>
  <div class="center">
    <table class="center gorodishes">
      <% @gorodishes.each do |g| %>
        <tr>
	  <td><span class="gorodish"><%= link_to g.element, g %></span></td>
	  <td>
            <% g.mnemonics.each do |m| %>
              <%= render m %>
            <% end %>
	  </td>
	</tr>
      <% end %>
    </table>
  </div>
<% end %>

app/views/hanzis/_tradsimp.html.erb
<% if @hanzi.traditional_variants.any? %>
  <h2><span class="hanzi"><%= @hanzi.character %></span> is the simplified version of 
  <% @hanzi.traditional_variants.each do |t| %>
    <%= link_to t.character, t, { class: "hanzi" } %>
  <% end %>.</h2>
<% elsif @hanzi.simplified_variants.any? %>
  <h2><span class="hanzi"><%= @hanzi.character %></span> is the traditional variant of 
  <% @hanzi.simplified_variants.each do |s| %>
    <%= link_to s.character, s, { class: "hanzi" } %>
  <% end %>.</h2>
<% else %>
  <h2><span class="hanzi"><%= @hanzi.character %></span> has no simplified variant.</h2>
<% end %>

app/views/hanzis/_words.html.erb
<h2>Words with <span class="hanzi"><%= @hanzi.character %></span></h2>
<%= will_paginate @words %>
<table class="words-table">
  <% @words.each do |w| %>
  <tr>
    <td class="word-characters">
      <% w.simplified.each_char.with_index do |c, i| %>
        <% pinyin = w.pinyin.split(" ")[i] %>
	<% colorclass = "" %>
	<% unless pinyin.nil? %>
	  <% colornumber = pinyin[-1] %>
 	  <% if colornumber =~ /[1-5]/ %>
	    <% colorclass = "color" + colornumber %>
	  <% end %>
        <% end %>
        <div style="display:inline-block;" class="center <%= colorclass %>">
          <%= link_to c, "/hurl/" + c, { class: "big-char hanzi #{colorclass}" } %>
	  <br/>
	  <%= pinyin %>
	</div>
      <% end %>
    </td>
    <td class="word-translation"><%= w.translation %>
      <% if w.HSK < 7 %>
	(HSK level <%= w.HSK %>)
      <% end %>
    </td>
  </tr>
  <% end %>
</table>
<%= will_paginate @words %>

app/views/hanzis/edit.html.erb
<% provide(:title, "Edit hanzi") %>
<h1>Update <span class="hanzi"><%= @hanzi.character %></span></h1>

<div class="center">
  <div class="center">
    <%= form_for(@hanzi) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      
      <%= f.label :components %>
      <%= f.text_field :components %>

      <div>
	Here are some basic strokes for copy-pasting:<br/>
	<span class="big-char hanzi">㇀㇁㇂㇃㇄㇅㇆㇇㇈㇉㇊㇋㇌㇍㇎㇏一丨<U+31D2></span>
      </div>
      <br/>
      <div>
	Hanzis without further decomposinition:<br/>
	<% @atoms.each do |a| %>
	  <span class="big-char hanzi"><%= a.character %></span>
	<% end %>
      </div>
      <br/>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/hanzis/index.html.erb
<% provide(:title, 'All hanzis') %>
<h1>All hanzis</h1>

<ul class="hanzis-ul">
  <% @hanzis.each do |hanzi| %>
    <li>
    <a href="/hanzis/<%= hanzi.id %>" class="big-char"><%= hanzi.character %></a>
    </li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/hanzis/select.html.erb
<h2>There are more than one featured images for <%= @hanzi.character %>. Choose one!</h2>
<% @fimages.each do |fimage| %>
  <% @hanzi = fimage.hanzi %>
  <div class="center feature">
    <a href="/featured_images/<%= fimage.id %>">
      <img src="http://<%= S3_CONFIG["fimage_bucket"] %>.s3-eu-west-1.amazonaws.com/<%= fimage.id %>.png"
	   alt="featured image for <%= @hanzi.character %>">
    </a>
    <div class="featured_mnemonic">
      <%= fimage.mnemonic_aide.html_safe %>
    </div>
  </div>
  <div><br/></div>
<% end %>

app/views/hanzis/show.html.erb
<% provide(:title, @hanzi.character) %>
<h1 class="hanzi"><%= @hanzi.character %></h1>

<% if signed_in? && current_user.admin? %>
  <div class="center">
    <br/>
    <%= link_to "Edit hanzi", edit_hanzi_path(@hanzi) %> | <%= link_to "New PD", new_pinyindefinition_path(:hanzi_id => @hanzi.id) %>
  </div>
<% end %>

<div class="center">
  <%= render @hanzi %>
</div>

<div class="center">
  <h2>Stroke order</h2>
  <% if !@stroke_order.nil? %>
    <a href="http://commons.wikimedia.org/wiki/Commons:Stroke_Order_Project" target="_blank">
      <%= image_tag @stroke_order, class: "stroke_order_image" %>
    </a>
  <% else %>
    No Wikimedia Commons Stroke Order Project data available yet.
  <% end %>
  </br>
  <% @strokeorders.each do |so| %>
    <div class="strokeorder">
    <% canvas_id = "stroke_order_canvas_#{so.id}" %>
    <% width = 200 %>
    <div><canvas id=<%= canvas_id %> height="<%= width %>" width="<%= width %>" class="center"></canvas></div>
    <%= render partial: "strokeorders/canvas", locals: { strokeorder_data: so.strokes, canvas_id: canvas_id, width: width } %>
    By <%= User.find(so.user_id).name %>, <%= time_ago_in_words(so.created_at) %> ago.
    </div>
  <% end %>
  <% if @strokeorders.empty? %>
    No user submitted stroke order information available yet.  
  <% end %>
  <% if signed_in? %>
    <div class="center">
      <%= link_to "Submit stroke order", { controller: "strokeorders", action: "new", hanzi_id: @hanzi.id } %>
    </div>
  <% else %>
    <br/><br/>Sign in to submit stroke order information.
  <% end %>    
</div>

<div class="center">
  <%= render partial: "appearance" %>
</div>

<div class="center">
  <%= render partial: "tradsimp" %>
</div>

<div class="center">
  <%= render partial: "hsk" %>
</div>

<div class="center">
  <%= render partial: "pronunciations" %>
</div>

<div class="center">
  <%= render partial: "words" %>
</div>

<% if @examples.any? %>
  <h2>Example sentences for <span class="hanzi"><%= @hanzi.character %></span></h2>
  <div class="center">
    <%= render partial: "subtitles/subtitle", collection: @examples, locals: {morelink: true, autoplay: 0, width: 250, height: 150, extensive: false} %>
  </div>
<% else %>
  <h2>There are no example sentences for <span class="hanzi"><%= @hanzi.character %></span>.</h2>
<% end %>

<h2>See <%= @hanzi.character %> on (opens in new window/tab)</h2>
<div class="center">
  <a target="_blank" href="http://hanzicraft.com/character/<%= @hanzi.character %>">Hanzicraft</a><br/>
  <a target="_blank" href="http://www.mdbg.net/chindict/chindict.php?page=worddict&wdrst=0&wdqb=<%= @hanzi.character %>">MDBG</a><br/>
  <a target="_blank" href="http://en.wikipedia.org/wiki/<%= @hanzi.character %>">The English Wikipedia</a><br/>
  <a target="_blank" href="https://en.wiktionary.org/wiki/<%= @hanzi.character %>">The English Wiktionary</a><br/>
  <a target="_blank" href="http://stroke-order.learningweb.moe.edu.tw/characterQueryResult.do?word=<%= @hanzi.character %>">stroke-order.learningweb.moe.edu.tw</a><br/>
  <a target="_blank" href="http://tatoeba.org/eng/sentences/search?query=<%= @hanzi.character %>&from=cmn&to=und">Tatoeba</a><br/>
  <a target="_blank" href="http://www.google.com/search?query=<%= @hanzi.character %>+stroke+order">Google search "<%= @hanzi.character %> stroke order"</a><br/>
  <a target="_blank" href="http://www.google.com/search?tbm=isch&query=<%= @hanzi.character %>+stroke+order">Google image search "<%= @hanzi.character %> stroke order"</a><br/>
</div>

<% if @hanzi.comments.any? %>
<div>
  <h2> Comments (<%= @hanzi.comments.count %>)</h2>
  <ol class="comments">
    <%= render @comments %>
  </ol>
</div>
<% end %>

<% if signed_in? %>
  <% if !@hanzi.comments.any? %>
    <h2>Write the first comment</h2>
  <% end %>
  <div>
    <%= render 'shared/comment_form' %>
  </div>
<% else %>
  <h2>Log in to write the first comment.</h2>
<% end %>